services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
  app:
    build: .
    image: 'springio/gs-spring-boot-docker'
    depends_on:
      - postgres
    ports:
      - 8080:8080
